package catalog

// Themes of loose bricks, by name at any level of a set's theme tree:
// buckets, tubs, brick boxes, service and supplementary packs, education
// packs, and the old basic sets, none of them a model of something.
var bulkThemes = map[string]bool{
	"Basic":                    true,
	"Classic Basic":            true,
	"Bricks & More":            true,
	"Bulk Bricks":              true,
	"Classic":                  true,
	"Educational and Dacta":    true,
	"Freestyle":                true,
	"Make & Create":            true,
	"Service Packs":            true,
	"Supplemental":             true,
	"System":                   true,
	"Universal Building Set":   true,
	"Value Packs":              true,
	"Building Set with People": true,
}

// Top-level themes made under license from another company's property.
var licensedThemes = map[string]bool{
	"Angry Birds":                      true,
	"Animal Crossing":                  true,
	"Avatar":                           true,
	"Avatar: The Last Airbender":       true,
	"Ben 10":                           true,
	"Bluey":                            true,
	"Cars":                             true,
	"DC Super Hero Girls":              true,
	"Despicable Me 4":                  true,
	"Dimensions":                       true,
	"Disney":                           true,
	"Fortnite":                         true,
	"Gabby's Dollhouse":                true,
	"Ghostbusters":                     true,
	"Harry Potter":                     true,
	"Horizon Adventures":               true,
	"Indiana Jones":                    true,
	"Jurassic World":                   true,
	"KPop Demon Hunters":               true,
	"Minecraft":                        true,
	"Minions":                          true,
	"Nike":                             true,
	"One Piece":                        true,
	"Overwatch":                        true,
	"Pokémon":                          true,
	"Scooby-Doo":                       true,
	"Shrek":                            true,
	"Sonic The Hedgehog":               true,
	"Speed Champions":                  true,
	"Speed Racer":                      true,
	"SpongeBob SquarePants":            true,
	"Star Wars":                        true,
	"Stranger Things":                  true,
	"Super Heroes DC":                  true,
	"Super Heroes Marvel":              true,
	"Super Mario":                      true,
	"Teenage Mutant Ninja Turtles":     true,
	"The Hobbit and Lord of the Rings": true,
	"The Legend of Zelda":              true,
	"The Lone Ranger":                  true,
	"The Powerpuff Girls":              true,
	"Trolls: World Tour":               true,
	"Wednesday":                        true,
	"Wicked":                           true,
}
