// Run in the browser console on rebrickable.com/build/, signed in, with the
// parts list to match against marked buildable. Searches free custom models
// (exact colors, then colors ignored), in bands of part count to get past the
// 500-result cap of one search, and keeps every result card in OUT.cards-ready
// form (OUT.searches). Then run 2-part-lists.js in the same page.
var OUT={searches:[],mocs:{},errors:[]}; var sl=t=>new Promise(r=>setTimeout(r,t)); var csrf=$("input[name=csrfmiddlewaretoken]").first().val(); var surl=$(".js-build-search").data("url"); var base=$.extend($("#default_build_options_form").serializeObject(),$("#build_search_form").serializeObject(),$("#build_source_form").serializeObject()); delete base.csrfmiddlewaretoken;
var post=async(url,params)=>{var data=$.param(params)+"&csrfmiddlewaretoken="+encodeURIComponent(csrf); var r=await $.ajax({url:url,type:"POST",data:data,cache:false}); var n=0; while(r&&r.poll_interval&&n<120){await sl(r.poll_interval); r=await $.ajax({url:r.poll_url,type:"POST",data:data,cache:false}); n++} return r};
var cards=h=>{var d=new DOMParser().parseFromString(h||"","text/html"); return Array.from(d.querySelectorAll(".js-build-search-result")).map(c=>{var a=c.querySelector("a"),im=c.querySelector("img"),t=c.textContent.replace(/\s+/g," ").trim(),m=t.match(/([\d.]+)%.*?Missing: (\d+) of (\d+) parts (.*)$/); return {href:a?a.href:"",img:im?(im.getAttribute("data-src")||im.getAttribute("src")):"",pct:m?+m[1]:null,missing:m?+m[2]:null,parts:m?+m[3]:null,name:m?m[4]:t}})};
var save=(name,obj)=>{var a=document.createElement("a"); a.href=URL.createObjectURL(new Blob([JSON.stringify(obj)])); a.download=name; a.click()};
(async()=>{ var buckets=[[0,60],[60,100],[100,160],[160,300],[300,5000]]; for(var color of [1,3]){for(var b of buckets){ var p=Object.assign({},base,{color:color,min_parts:b[0],max_parts:b[1],inc_custom:1,inc_alts:1,sort_by:1,min_year:1945,max_year:2027,added_days_ago:366}); delete p.inc_official; delete p.inc_premium; delete p.job; delete p.page; try{ var r=await post(surl,p); var job=r.job_id; var got=cards(r.html); var all=got.slice(); for(var pg=2;pg<=9&&got.length;pg++){ r=await post(surl,Object.assign({},p,{job:job,page:pg})); got=cards(r.html); all=all.concat(got) } OUT.searches.push({color:color,min:b[0],max:b[1],job:job,results:all}); console.log("search color "+color+" "+b[0]+"-"+b[1]+": "+all.length) }catch(e){OUT.errors.push("search "+color+" "+b+": "+e); console.log("search failed "+e)} }}
 save("rb-searches.json",OUT.searches); console.log("searched: "+OUT.searches.map(x=>x.results.length).join(", ")) })()
